pasqal-io/pyqtorch

pyqtorch/converters/to_qiskit.py, pyqtorch/core/batched_operation.py, pyqtorch/core/operation.py, pyqtorch/core/utils.py, tests/test_operations.py
- Added gates S, T, CPHASE, SWAP ,CRY, CRX, CRZ
- Added tests for CNOT, CRY
- Refactored operation.py and add generic controlled operations
- Added batchedCphase gate 
Closes #17 and closes #15
=> Additional Gates

pyqtorch/core/batched_operation.py
Simple fix on how the batched evolution handled the values of the time parameter.
=> Ham evo bug fix

pyqtorch/core/operation.py, tests/test_operations.py
This PR addresses the addition of the identity in `pyqtorch.core.operations`.
=> Add and test identity operation.

.pre-commit-config.yaml, pyproject.toml, pyqtorch/core/operation.py, pyqtorch/core/utils.py, pyqtorch/modules/__init__.py, pyqtorch/modules/hamevo.py, pyqtorch/modules/parametric.py, pyqtorch/modules/primitive.py, tests/test_module_hamevo.py, tests/test_modules.py
pyq.modules:
- Bumped torch version to 2.0.0
- Added CZ,CY
- Added MultiParamRotationGate with batched U gate
- Added batched HamEvo, batched HamEvoEig
- Added tests for circuits, gates
=> Module API - New gates

pyproject.toml, pyqtorch/modules/__init__.py, pyqtorch/modules/circuit.py, pyqtorch/modules/hamevo.py, tests/test_module_hamevo.py, tests/test_modules.py
closes https://github.com/pasqal-io/PyQ/issues/49
closes https://github.com/pasqal-io/PyQ/issues/52
=> Fixed bug in QuantumCircuit device, added buffer-free HamEvo

pyqtorch/core/operation.py, pyqtorch/core/utils.py, pyqtorch/modules/__init__.py, pyqtorch/modules/primitive.py, tests/test_modules.py
Need to support Sdagger in PyQTorch.
=> Add sdagger op

pyqtorch/core/operation.py, pyqtorch/modules/__init__.py, pyqtorch/modules/primitive.py, tests/test_modules.py
The implementation of Toffoli gates and the possibility to create multi controlled gates.
=> Toffoli gates

pyqtorch/core/batched_operation.py, pyqtorch/modules/parametric.py, tests/test_modules.py
This Pull Request introduces the possibility to have multiple control qubits for any controlled gate in pyq namely the CRX, CRY, CRZ & CPHASE gates.
=> Multi controlled op

pyqtorch/core/batched_operation.py
I realise I made this small mistake on a previous PR some months ago
=> Clear up misleading variable naming.

pyproject.toml, pyqtorch/adjoint.py, pyqtorch/matrices.py
Added missing dtype to matrix inits which causes issues in qadence. added no_grad decorator to first order adjoint, bump version
=> [Fix] Matrix precision and use no_grad in adjoint

pyqtorch/__init__.py, pyqtorch/matrices.py, pyqtorch/primitive.py, tests/test_digital.py
=> Add single qubit projector.

docs/index.md, pyproject.toml, pyqtorch/circuit.py, pyqtorch/primitive.py
- Add `to(device` method to gates
- Add `_device` field, and device `property` to QuantumCircuit and gates
=> [Refac] Add device to Gates

pyqtorch/adjoint.py, tests/test_circuit.py
Fixes https://github.com/pasqal-io/pyqtorch/issues/149
=> [Fix] Correct gradients for duplicate parameters in Adjoint

pyproject.toml, pyqtorch/__init__.py, pyqtorch/adjoint.py, pyqtorch/circuit.py, pyqtorch/parametric.py, pyqtorch/utils.py, tests/test_circuit.py
Moving several key, higher-order block operations from qadence to pyqtorch.
Namely `Add`, `Scale` and `Merge`
=> [Feature] Add higher order operations

pyqtorch/utils.py, tests/test_digital.py
Resolved the bug report #168 by adding `operator_kron()` function in `utils.py`.
Closed #168.
=> [Bug] Add Operator Kronecker product 

pyqtorch/utils.py
=> [Refac] Remove batch_first and batch_last functions

docs/adjoint.md, docs/extras/css/colors.css, docs/extras/css/home.css, docs/extras/css/mkdocstrings.css, docs/extras/javascripts/mathjax.js, docs/extras/overrides/home.html, docs/index.md, docs/noise.md, mkdocs.yml
FIx missing code snippets not being shown
=> [Fix] Docs display

mkdocs.yml, pyqtorch/__init__.py
Add sesolve and mesolve to main namespace.
=> Add sesolve and mesolve to main namespace

pyproject.toml, pyqtorch/__init__.py, pyqtorch/circuit.py, tests/test_circuit.py
- Exposing functional-style `run`, `sample` methods
- Adding a `state_from_bitstring` method to `QuantumCircuit`
=> [Feature] Add run, sample and from_bitstring

tests/test_digital.py
=> [Testing] Improve projector tests

pyqtorch/gpsr.py, tests/test_circuit.py
Closes #217
Just needed to reset the dict values by readding a shift.
Also added the repeated params case in tests.
=> [Bug] Fix GPSR with repeated params

pyproject.toml, pyqtorch/parametric.py, pyqtorch/primitive.py, tests/test_digital.py
To avoid calculating eigenvalues for several parametric operations.
=> [Refactor] Add eigenvals_generator for parametric operations

tests/test_differentiation.py
Just testing further PSR for different batch sizes, dtype, observables + going through all possible elements for the gradient components to test higher order grads.
=> [Testing] Expand test psr single gap

docs/analog.md, docs/index.md, pyqtorch/analog.py
=> [Documentation] Add a note about units

pyqtorch/embed.py
Closes #229.
The issue description is outdated. Some minor improvements to the codebase.
=> [Refactor] Minor improvements to type annotations and initialisations.

pyqtorch/matrices.py, pyqtorch/parametric.py
=> [Bug] Add permute basis parametric

pyqtorch/differentiation/gpsr.py
Fixes #258 where not only one should multiply by 2 the spectral gap, but also adjust the shift accordingly for single gap cases.
=> [Bugfix] Adjust shift with hamevo via a prefactor

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/new-feature.yml, pyproject.toml
=> [Feature] Add issue template

pyproject.toml, pyqtorch/__init__.py, pyqtorch/api.py, pyqtorch/circuit.py, pyqtorch/composite/compose.py, pyqtorch/hamiltonians/evolution.py, pyqtorch/hamiltonians/observable.py, pyqtorch/primitives/parametric.py, pyqtorch/utils.py, tests/test_embedding.py, tests/test_noise.py
Closes https://github.com/pasqal-io/pyqtorch/issues/172
=> [Feature] Add noise expectation

pyproject.toml, pyqtorch/noise/__init__.py, pyqtorch/noise/gates.py, pyqtorch/noise/protocol.py, pyqtorch/primitives/parametric.py, pyqtorch/primitives/parametric_gates.py, pyqtorch/primitives/primitive.py, pyqtorch/primitives/primitive_gates.py, pyqtorch/quantum_operation.py, tests/conftest.py, tests/helpers.py, tests/test_analog.py
Closes https://github.com/pasqal-io/pyqtorch/issues/252
=> [Refact] NoiseProtocol with list of noise types

pyqtorch/__init__.py
Removing logger message at import of pyqtorch.
=> [Improvement] Remove message logger loaded successfully

pyqtorch/composite/compose.py, tests/test_circuit.py
=> [Bug] Fix Merge in case of noisy operations

pyqtorch/api.py, tests/test_differentiation.py
=> [Bugfix] Support density matrices for sampled expectation

.github/workflows/test.yml, README.md, pyproject.toml
=> [Docs] Add coverage badge to PyQTorch.

.github/workflows/test.yml, pyproject.toml
Minor fix to trigger correct coverage.
=> [Docs] Delete unnecessary line as coverage should be automated.

pyqtorch/primitives/primitive_gates.py
Patch for the mutable N that makes qadence tests fail.
=> [Bugfix] Clone state in mutable N

tests/conftest.py, tests/primitives/test_tensor.py, tests/test_circuit.py, tests/test_embedding.py
**Closes #272**
This PR implements comprehensive testing for the `Embedding` class functionality as requested in issue #272. The implementation provides thorough verification that embeddings work correctly across all supported quantum operations in pyqtorch.
**✅ Tests Added:**
- **`tests/conftest.py`**: Added `embedding_fixture` implementing the exact example from the issue (`y * sin(x)`)
- **`tests/test_circuit.py`**: `test_embedding_with_composite_gates()` - Tests Sequence, Add, Scale operations
- **`tests/primitives/test_tensor.py`**: `test_param_gate_embed()` - Tests all parametric gates in `OPS_PARAM`
- **`tests/test_embedding.py`**: 
- `test_sample_run_expectation_grads_with_embedding_observable()` - Observable expectation with embedded parameters
- …
=> [Testing] Expand embedding tests for all operators #272
