pasqal-io/pyqtorch

pyqtorch/modules/circuit.py, pyqtorch/modules/hamevo.py, pyqtorch/modules/parametric.py, pyqtorch/modules/primitive.py
Infer device for initial state creation from `model.parameters` directly and don't go via a custom `model.device` property in every gate.
=> Remove device attribute from gates

pyqtorch/modules/__init__.py, pyqtorch/modules/hamevo.py, pyqtorch/modules/utils.py, tests/test_module_hamevo.py
Current hamevo with diagonalization has unstable gradients in some optimization routines. Using `torch.linalg.matrix_exp` seems to be quite fast and should solve the unstable gradients.
=> Add hamevo with torch.linalg.matrix_exp

pyqtorch/core/utils.py
This PR addresses the addition of a data type to correctly infer the type. This avoids errors:
```python
>           torch.tensor(state_dims + [j for j in range(N_qubits + 1) if j not in state_dims])
)
E       RuntimeError: Could not infer dtype of Zero
```
=> [BugFix] Fix type inference error.

pyqtorch/core/utils.py
Another PR in the same vein: specifying `dtype` to avoid errors:
```python
>       mat_indices[len(qubits) : 2 * len(qubits)] = state_indices[qubits]
E
```
because:
```
qubits = array([0], dtype=object)
```
=> Correct tensor type

pyproject.toml, pyqtorch/modules/hamevo.py, tests/test_module_hamevo.py
hamevo has incorrect endianness... as shown below. this PR fixes this with a bit of a hacky endianness inversion in `HamEvo`...
```python
op = pyq.HamEvoExp(H0, torch.tensor([1.0]), qubits=[0,1], n_qubits=2)
print(H0)
print(op(pyq.zero_state(2)).flatten())
op = pyq.HamEvoExp(H1, torch.tensor([1.0]), qubits=[0,1], n_qubits=2)
print(H1)
print(op(pyq.zero_state(2)).flatten())
```
=> `HamEvo` endianness

docs/index.md, pyproject.toml, pyqtorch/__init__.py, pyqtorch/analog.py, pyqtorch/circuit.py, pyqtorch/primitive.py, pyqtorch/utils.py
=> [Feature] Debug logging and NVTX annotations

pyqtorch/parametric.py, pyqtorch/primitive.py, tests/test_circuit.py, tests/test_digital.py
=> [Refactor] Correct behaviour of CSWAP constructor

pyproject.toml, pyqtorch/circuit.py, tests/test_circuit.py
avoid inferring batch_sizes from the length of dicts as values
=> [Fix] Handle nested param dicts

pyqtorch/analog.py
Due to `param_name` possibly be a tensor, we should overload the `to` method for `Scale` for conversion purposes.
=> [Fix] Overload `to` method of pyq.Scale

pyqtorch/gpsr.py, tests/test_circuit.py
Handles #217 by only doing PSR on the current operation in loop to handle repeated param_name.
=> [Bug] Fix GPSR with repeated params

pyqtorch/analog.py, tests/test_analog.py
Avoid recomputing the evolution operator via a simple caching system. Related to issue #176
=> [Refactoring, Hamevo] Optimize block_to_tensor calls for repeated execution of HamEvo

pyqtorch/gpsr.py, tests/test_differentiation.py
Fix the `if` order in `check_support_psr` to avoid checking the spectral gap for other unconcerned gates, which raises an error.
=> [Bug] Fix check support PSR

pyqtorch/utils.py, tests/test_embedding.py
The pipeline may fail at precision `1e-06`. So reducing it to 3.
=> [Testing] Increase cross-platform embedding atol

pyproject.toml, pyqtorch/adjoint.py, pyqtorch/analog.py, pyqtorch/circuit.py, pyqtorch/generic_quantum_ops.py, pyqtorch/matrices.py, pyqtorch/parametric.py, pyqtorch/primitive.py, pyqtorch/quantum_ops.py, pyqtorch/utils.py, tests/test_digital.py
To tackle issue #240 : 
Such class requires a tensor operator and a function to get a basic operator representation, to be used later in the tensor method. Doing so, we can define both Primitive and Parametric quantum operations, but probably more custom/advanced quantum operations later.
=> [Refact] Consistent base classes

pyqtorch/differentiation/gpsr.py
To account for the factor 2 between the definition of `HamiltonianEvolution` and usual `Parametric` gates, one needs to rescale the shift with the spectral gap on top of dividing by 2.
=> [Bugfix] Divide shift by spectral gap for single-gap PSR

pyqtorch/api.py, pyqtorch/apply.py, pyqtorch/composite/sequence.py, pyqtorch/hamiltonians/evolution.py, pyqtorch/quantum_operation.py, pyqtorch/utils.py, tests/helpers.py, tests/test_tensor.py
A few things that came up while working on the improvement to the noise.
- The `permute_basis` was not doing the correct permutation, but it was going unnoticed because the `expand_operator` was compensating for it.
- I created an alternative `apply_operator_permute` which is just as fast as the `apply_operator` function, but can serve as a basis for future changes. For now we can simply save it. It could be useful if we wish to make PyQ follow the more standard state shape of `[batch_size, 2**n_qubits]` instead of the `[2] * n_qubits + [batch_size]`. The reason I wrote it is because the logic I am working on for the `apply_density_mat` follows something similar, but doing it first for the normal `apply_operator` was easier.
=> [Bug, Feature] Fix permute basis and add permutation based apply operator

pyproject.toml, pyqtorch/__init__.py, pyqtorch/composite/compose.py, pyqtorch/differentiation/adjoint.py, pyqtorch/embed.py, pyqtorch/hamiltonians/evolution.py, pyqtorch/primitives/parametric.py, pyqtorch/utils.py, tests/helpers.py, tests/test_analog.py, tests/test_digital.py, tests/test_embedding.py, tests/test_utils.py
Extends the `ConcretizedCallable` to allow nested calls, adds some convenience functions. E.g. now we can write
```
import pyqtorch as pyq
expr = "z" ** pyq.log(1.0 / (1.0 + (2.0 * pyq.sin("x")) + "y"))
expr_name = "expr"
embedding = pyq.Embedding(
fparam_names = ["x", "y"],
vparam_names = ["z"],
var_to_call = {"expr": expr}
)
op = pyq.Scale(pyq.I(0), "expr")
values = {"x": torch.tensor(1.0), "y": torch.tensor(-1.0),  "z": torch.tensor(2.0)}
matrix = op.tensor(values, embedding)
matrix[..., 0]
---
tensor([[0.6971, 0.0000],
[0.0000, 0.6971]])
```
Furthermore, with the current change, we might not need the `Embedding` 🤔. To be explored in a later MR: https://github.com/pasqal-io/pyqtorch/issues/278
=> [Feature, Testing] Allow nested calls to ConcretizedCallable, more tests

pyproject.toml, pyqtorch/hamiltonians/evolution.py, tests/conftest.py, tests/test_analog.py
This MR gives the same interface to the `duration` argument of other PyQ parameters, where you can define it as a string and then pass the actual value in the values dict. This allows to define the duration of the time-dependent integration only at runtime, like so:
```
from pyqtorch import X, HamiltonianEvolution, Scale
from pyqtorch import random_state
import torch
hamiltonian = Scale(X(0), "t")
evo = HamiltonianEvolution(hamiltonian, "t", duration = "duration")
state = random_state(2)
values = {"duration": 0.2}
evo(state, values = values)
```
=> [Feature] Allow time-dependent duration to be passed at runtime

pyqtorch/differentiation/gpsr.py, tests/test_analog.py
Following this [Qadence MR](https://github.com/pasqal-io/qadence/pull/616), where I quote @vytautas-a :
`I suspect that due to some symmetries in matrices computed during GPSR calculations, results with some generators are not correct. Breaking this symmetry of shifts around pi/2 helps in this regard.`
Changing the interval for multigap GPSR to not be symmetric.
=> [Bugfix] Changing shift interval for multigap GGPSR

.github/workflows/test.yml, docs/noise.md, pyqtorch/api.py, pyqtorch/circuit.py, pyqtorch/noise/__init__.py, pyqtorch/noise/readout.py, tests/test_readout.py
Closes #285 by adding correlated readout. Also, we extend ReadoutNoise to provide different `error_probability` tensors. Now we can provide a 1D tensor where each qubit has a different probability of corruption. Also we can provide a tensor of shape (n_qubits, 2, 2) that avoids recomputing the confusion_matrix if someone is interested in providing it from data, but we can still create noise matrices for corruption.
=> [Feature] Correlated readout and extending ReadoutNoise

pyqtorch/circuit.py
Related to #296. 
Using the apply method on the probability vector directly in `QuantumCircuit.sample` leads to faster runtime (example on 10 qubits for 1e6 shots leads to runtime in ms instead of seconds).
=> [Feature] Faster sample method with readout

pyqtorch/circuit.py
circuit.sample was incorrect as there were two instructions for obtaining probabilities. We only need one instructions depending on whether we have a dendity matrix or a state vector.
=> [BugFix] circuit.sample fix

pyqtorch/noise/readout.py, tests/test_readout.py
Solving the edge case when mean of an empty tensor returns nan
=> [Bugfix] Fix mean when empty tensor for readout

.github/workflows/test.yml, pyproject.toml
This is needed as version upgrade to Python3.13 in Qadence fails due to being unsupported here.
=> [Feature] Update python to 3.13

pyqtorch/composite/compose.py, pyqtorch/composite/sequence.py, pyqtorch/hamiltonians/evolution.py, pyqtorch/primitives/primitive_gates.py, tests/differentiation/test_differentiation.py, tests/differentiation/test_gpsr.py, tests/helpers.py, tests/noise/test_noise.py, tests/primitives/test_tensor.py, tests/test_analog.py, tests/test_circuit.py, tests/test_embedding.py
=> [Feature, Performance] Optimize HamiltonianEvolution for commuting hamiltonians

tests/test_analog.py
**Repository:** pasqal-io/pyqtorch  
**Issue:** [#273 - Test parameter re-embedding in HamiltonianEvolution](https://github.com/pasqal-io/pyqtorch/issues/273)  
**Status:** ✅ **COMPLETED** - Fully validated with comprehensive tests
---
The parameter re-embedding functionality in PyQTorch's time-dependent `HamiltonianEvolution` has been **comprehensively validated** through 5 new test functions. All tests pass successfully, confirming that the optimization works correctly across all scenarios including basic expressions, complex nested dependencies, quantum state evolution, edge cases, and sustained numerical precision.
**Key Achievement:** Mathematical equivalence proven to 1e-14 precision between full embedding and re-embedding approaches.
---
> *"La dependencia del tiempo …
=> [Testing] Test reembedding of params in HamiltonianEvolution #273
